version: "3.7"

services:
  influxdb:
    image: "influxdb:2.0"
    volumes:
      - ../influxdb2:/var/lib/influxdb2
      - ./influx-config.yml:/etc/influxdb2/config.yml
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=cloudnative
      - DOCKER_INFLUXDB_INIT_PASSWORD=cloudnative_influx
      - DOCKER_INFLUXDB_INIT_ORG=cloud17
      - DOCKER_INFLUXDB_INIT_BUCKET=steak
      - DOCKER_INFLUXDB_INIT_MODE=setup
    ports:
      - 8086:8086
  grafana:
    image: "grafana/grafana-oss"
    volumes:
      - ../grafana/data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
    ports:
      - 3000:3000


