apiVersion: v1
kind: Pod
metadata:
  name: cnfpb-node2-pod
  labels:
    app: cnfpb-node2
spec:
  containers:
    - name: cnfpb-node2
      image: howhow8765/cnfpb-node:latest
      env:
      - name: NODE_ID
        value: "2"
      ports:
      - containerPort: 8081