apiVersion: v1
kind: Pod
metadata:
  name: cnfpb-node1-pod
  labels:
    app: cnfpb-node1
spec:
  containers:
    - name: cnfpb-node1
      image: howhow8765/cnfpb-node:latest
      env:
      - name: NODE_ID
        value: "1"
      ports:
      - containerPort: 8081