{
 "title": "Steak",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Steak",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"steak\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"steak\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"recipe\")\r\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Steak Complete",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"steak\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"steak\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Oven Temperature Gauge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"steak\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"oven\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Steak",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"steak\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patch\" and r._field != \"recipe\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Oven Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"steak\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"oven\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")"
    }
   ]
  }
 ]
}