name: Build and Push to Dockerhub
on:
  push:
    branches:    
      - 'main'
    paths:
      - 'RecipeDispatcher/**'
      - 'Node/**'
  workflow_dispatch:
jobs:
  login-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - uses: dorny/paths-filter@v2
      id: changes
      with:
         filters: |
            RecipeDispatcher:
              - 'RecipeDispatcher/**'
            Node:
              - 'Node/**'
            Grafana:
              - 'grafana/**'

    - name: RecipeDispatcher Build and push
      if: ${{ (steps.changes.outputs.RecipeDispatcher == 'true') || (github.event_name == 'workflow_dispatch') }} 
      uses: docker/build-push-action@v2
      with:
          context: ./RecipeDispatcher
          file: ./RecipeDispatcher/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cnfpb-recipe-dispatcher:latest
    
    - name: Node Build and push
      if: ${{ (steps.changes.outputs.Node == 'true') || (github.event_name == 'workflow_dispatch') }}
      uses: docker/build-push-action@v2
      with:
          context: ./Node
          file: ./Node/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cnfpb-node:latest
    
    - name: Grafana Build and push
      if: ${{ (steps.changes.outputs.Grafana == 'true') || (github.event_name == 'workflow_dispatch') }}
      uses: docker/build-push-action@v2
      with:
          context: ./grafana
          file: ./grafana/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cnfpb-grafana:latest
